[fmt]
quote_style = 'single'
single_line_statement_blocks = 'single'

[profile.default]
solc = '0.8.14'
src = './solidity'
test = './solidity/test'
out = 'out'
libraries = []
cache = true
evm_version = 'london'
gas_reports = ['*']
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 0
fuzz_runs = 1000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
